//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Strings.resx by tools/generate-strings.ps1 — do not edit by
//     hand; rerun the script after changing the resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMaid.Lang;

/// <summary>
/// Strongly-typed accessors for the UI string resources in <c>Lang\Strings.resx</c>
/// (dots in resource keys become underscores). Lookups follow
/// <see cref="System.Globalization.CultureInfo.CurrentUICulture"/>, which
/// <c>Localizer.Apply</c> switches at runtime; a missing key falls back to the key
/// itself so a lookup can never throw or return null.
/// </summary>
public static class Strings
{
    /// <summary>The underlying resource manager (used by <c>Localizer</c> for keyed lookups).</summary>
    public static global::System.Resources.ResourceManager ResourceManager { get; } =
        new("SyncMaid.Lang.Strings", typeof(Strings).Assembly);

    private static string Get(string key) =>
        ResourceManager.GetString(key, global::System.Globalization.CultureInfo.CurrentUICulture) ?? key;

    /// <summary>Looks up a localized string similar to "Add".</summary>
    public static string Common_Add => Get("Common.Add");

    /// <summary>Looks up a localized string similar to "Browse".</summary>
    public static string Common_Browse => Get("Common.Browse");

    /// <summary>Looks up a localized string similar to "Cancel".</summary>
    public static string Common_Cancel => Get("Common.Cancel");

    /// <summary>Looks up a localized string similar to "Delete".</summary>
    public static string Common_Delete => Get("Common.Delete");

    /// <summary>Looks up a localized string similar to "{0} file".</summary>
    public static string Common_FilesCount_One => Get("Common.FilesCount.One");

    /// <summary>Looks up a localized string similar to "{0} files".</summary>
    public static string Common_FilesCount_Other => Get("Common.FilesCount.Other");

    /// <summary>Looks up a localized string similar to "A Move destination must be the only destination of its task.".</summary>
    public static string Common_MoveExclusiveHint => Get("Common.MoveExclusiveHint");

    /// <summary>Looks up a localized string similar to "Name".</summary>
    public static string Common_NameLabel => Get("Common.NameLabel");

    /// <summary>Looks up a localized string similar to "Delete destination".</summary>
    public static string Dest_DeleteTip => Get("Dest.DeleteTip");

    /// <summary>Looks up a localized string similar to "Edit destination".</summary>
    public static string Dest_EditTip => Get("Dest.EditTip");

    /// <summary>Looks up a localized string similar to "{0} filters".</summary>
    public static string Dest_FiltersCountFormat => Get("Dest.FiltersCountFormat");

    /// <summary>Looks up a localized string similar to "Add group".</summary>
    public static string DestEditor_AddGroup => Get("DestEditor.AddGroup");

    /// <summary>Looks up a localized string similar to "Combine groups to express e.g. (docs or photos) and jpg".</summary>
    public static string DestEditor_AddGroupTip => Get("DestEditor.AddGroupTip");

    /// <summary>Looks up a localized string similar to "Copy new and changed files; never delete from the destination.".</summary>
    public static string DestEditor_AddOnlyDesc => Get("DestEditor.AddOnlyDesc");

    /// <summary>Looks up a localized string similar to "all rules".</summary>
    public static string DestEditor_AllRules => Get("DestEditor.AllRules");

    /// <summary>Looks up a localized string similar to "A file matches this group only when every rule matches (AND)".</summary>
    public static string DestEditor_AllRulesTip => Get("DestEditor.AllRulesTip");

    /// <summary>Looks up a localized string similar to "any rule".</summary>
    public static string DestEditor_AnyRule => Get("DestEditor.AnyRule");

    /// <summary>Looks up a localized string similar to "A file matches this group when any rule matches (OR)".</summary>
    public static string DestEditor_AnyRuleTip => Get("DestEditor.AnyRuleTip");

    /// <summary>Looks up a localized string similar to "Ask when deleting more than".</summary>
    public static string DestEditor_AskWhenDeletingMoreThan => Get("DestEditor.AskWhenDeletingMoreThan");

    /// <summary>Looks up a localized string similar to "Confirm before a large deletion".</summary>
    public static string DestEditor_ConfirmLargeDeletions => Get("DestEditor.ConfirmLargeDeletions");

    /// <summary>Looks up a localized string similar to "When removing extra files".</summary>
    public static string DestEditor_DeleteModeLabel => Get("DestEditor.DeleteModeLabel");

    /// <summary>Looks up a localized string similar to "This folder overlaps a destination of task &quot;{0}&quot; — tasks never share destinat...".</summary>
    public static string DestEditor_DestinationOverlapHintFormat => Get("DestEditor.DestinationOverlapHintFormat");

    /// <summary>Looks up a localized string similar to "Exclude — sync everything except files matching this rule".</summary>
    public static string DestEditor_ExcludeTip => Get("DestEditor.ExcludeTip");

    /// <summary>Looks up a localized string similar to "Files to sync".</summary>
    public static string DestEditor_FilesToSyncLabel => Get("DestEditor.FilesToSyncLabel");

    /// <summary>Looks up a localized string similar to "Destination folder".</summary>
    public static string DestEditor_FolderLabel => Get("DestEditor.FolderLabel");

    /// <summary>Looks up a localized string similar to "Match all groups".</summary>
    public static string DestEditor_MatchAllGroups => Get("DestEditor.MatchAllGroups");

    /// <summary>Looks up a localized string similar to "Sync only files that match every group".</summary>
    public static string DestEditor_MatchAllGroupsTip => Get("DestEditor.MatchAllGroupsTip");

    /// <summary>Looks up a localized string similar to "Match any group".</summary>
    public static string DestEditor_MatchAnyGroup => Get("DestEditor.MatchAnyGroup");

    /// <summary>Looks up a localized string similar to "Sync files that match at least one group".</summary>
    public static string DestEditor_MatchAnyGroupTip => Get("DestEditor.MatchAnyGroupTip");

    /// <summary>Looks up a localized string similar to "Match".</summary>
    public static string DestEditor_MatchLabel => Get("DestEditor.MatchLabel");

    /// <summary>Looks up a localized string similar to "Keep the destination identical — copies new and changed files, deletes extras.".</summary>
    public static string DestEditor_MirrorDesc => Get("DestEditor.MirrorDesc");

    /// <summary>Looks up a localized string similar to "This folder doesn&apos;t exist yet — it will be created on the first run. Double-c...".</summary>
    public static string DestEditor_MissingFolderHint => Get("DestEditor.MissingFolderHint");

    /// <summary>Looks up a localized string similar to "Move matching files to the destination, removing them from the source.".</summary>
    public static string DestEditor_MoveDesc => Get("DestEditor.MoveDesc");

    /// <summary>Looks up a localized string similar to "Destination must be a separate folder outside the source (and not contain it).".</summary>
    public static string DestEditor_NestedPathHint => Get("DestEditor.NestedPathHint");

    /// <summary>Looks up a localized string similar to "Only matching".</summary>
    public static string DestEditor_OnlyMatching => Get("DestEditor.OnlyMatching");

    /// <summary>Looks up a localized string similar to "e.g. photos/2024 or jpg".</summary>
    public static string DestEditor_PatternPlaceholder => Get("DestEditor.PatternPlaceholder");

    /// <summary>Looks up a localized string similar to "% of the destination".</summary>
    public static string DestEditor_PercentOfDestination => Get("DestEditor.PercentOfDestination");

    /// <summary>Looks up a localized string similar to "Remove group".</summary>
    public static string DestEditor_RemoveGroupTip => Get("DestEditor.RemoveGroupTip");

    /// <summary>Looks up a localized string similar to "Remove".</summary>
    public static string DestEditor_RemoveTip => Get("DestEditor.RemoveTip");

    /// <summary>Looks up a localized string similar to "Save destination".</summary>
    public static string DestEditor_Save => Get("DestEditor.Save");

    /// <summary>Looks up a localized string similar to "Sync strategy".</summary>
    public static string DestEditor_StrategyLabel => Get("DestEditor.StrategyLabel");

    /// <summary>Looks up a localized string similar to "Destination".</summary>
    public static string DestEditor_Title => Get("DestEditor.Title");

    /// <summary>Looks up a localized string similar to "Verification".</summary>
    public static string DestEditor_VerificationLabel => Get("DestEditor.VerificationLabel");

    /// <summary>Looks up a localized string similar to "Verify file contents (xxHash) after each copy".</summary>
    public static string DestEditor_VerifyContents => Get("DestEditor.VerifyContents");

    /// <summary>Looks up a localized string similar to "This is a network location. Content verification re-reads every copied file o...".</summary>
    public static string DestEditor_VerifyNetworkWarning => Get("DestEditor.VerifyNetworkWarning");

    /// <summary>Looks up a localized string similar to "Select Destination Folder".</summary>
    public static string Dialog_SelectDestinationFolder => Get("Dialog.SelectDestinationFolder");

    /// <summary>Looks up a localized string similar to "Select Source Folder".</summary>
    public static string Dialog_SelectSourceFolder => Get("Dialog.SelectSourceFolder");

    /// <summary>Looks up a localized string similar to "Delete permanently".</summary>
    public static string Enum_DeleteMode_Permanent => Get("Enum.DeleteMode.Permanent");

    /// <summary>Looks up a localized string similar to "Recycle Bin".</summary>
    public static string Enum_DeleteMode_Recycle => Get("Enum.DeleteMode.Recycle");

    /// <summary>Looks up a localized string similar to "Extension".</summary>
    public static string Enum_FilterKind_Extension => Get("Enum.FilterKind.Extension");

    /// <summary>Looks up a localized string similar to "Path".</summary>
    public static string Enum_FilterKind_Path => Get("Enum.FilterKind.Path");

    /// <summary>Looks up a localized string similar to "Add-only".</summary>
    public static string Enum_SyncStrategy_AddOnly => Get("Enum.SyncStrategy.AddOnly");

    /// <summary>Looks up a localized string similar to "Mirror".</summary>
    public static string Enum_SyncStrategy_Mirror => Get("Enum.SyncStrategy.Mirror");

    /// <summary>Looks up a localized string similar to "Move".</summary>
    public static string Enum_SyncStrategy_Move => Get("Enum.SyncStrategy.Move");

    /// <summary>Looks up a localized string similar to "All files".</summary>
    public static string Filter_AllFiles => Get("Filter.AllFiles");

    /// <summary>Looks up a localized string similar to "all files".</summary>
    public static string Filter_AllFilesInline => Get("Filter.AllFilesInline");

    /// <summary>Looks up a localized string similar to "and".</summary>
    public static string Filter_And => Get("Filter.And");

    /// <summary>Looks up a localized string similar to "Exclude — {0}".</summary>
    public static string Filter_ExcludeRowFormat => Get("Filter.ExcludeRowFormat");

    /// <summary>Looks up a localized string similar to "Extension: {0}".</summary>
    public static string Filter_ExtensionRowFormat => Get("Filter.ExtensionRowFormat");

    /// <summary>Looks up a localized string similar to "No rules yet — nothing will be synced.".</summary>
    public static string Filter_NoRulesPreview => Get("Filter.NoRulesPreview");

    /// <summary>Looks up a localized string similar to "not".</summary>
    public static string Filter_Not => Get("Filter.Not");

    /// <summary>Looks up a localized string similar to "nothing".</summary>
    public static string Filter_Nothing => Get("Filter.Nothing");

    /// <summary>Looks up a localized string similar to "or".</summary>
    public static string Filter_Or => Get("Filter.Or");

    /// <summary>Looks up a localized string similar to "Path: {0}".</summary>
    public static string Filter_PathRowFormat => Get("Filter.PathRowFormat");

    /// <summary>Looks up a localized string similar to "Syncs: {0}".</summary>
    public static string Filter_SyncsPreviewFormat => Get("Filter.SyncsPreviewFormat");

    /// <summary>Looks up a localized string similar to "Close".</summary>
    public static string Main_CloseTip => Get("Main.CloseTip");

    /// <summary>Looks up a localized string similar to "Collapse all".</summary>
    public static string Main_CollapseAll => Get("Main.CollapseAll");

    /// <summary>Looks up a localized string similar to "Delete the task &quot;{0}&quot; and {1}? This can&apos;t be undone.".</summary>
    public static string Main_DeleteTaskMessageFormat => Get("Main.DeleteTaskMessageFormat");

    /// <summary>Looks up a localized string similar to "its 1 destination".</summary>
    public static string Main_DeleteTaskSuffix_One => Get("Main.DeleteTaskSuffix.One");

    /// <summary>Looks up a localized string similar to "its {0} destinations".</summary>
    public static string Main_DeleteTaskSuffix_Other => Get("Main.DeleteTaskSuffix.Other");

    /// <summary>Looks up a localized string similar to "Delete task?".</summary>
    public static string Main_DeleteTaskTitle => Get("Main.DeleteTaskTitle");

    /// <summary>Looks up a localized string similar to "Expand all".</summary>
    public static string Main_ExpandAll => Get("Main.ExpandAll");

    /// <summary>Looks up a localized string similar to "Hide sidebar".</summary>
    public static string Main_HideSidebarTip => Get("Main.HideSidebarTip");

    /// <summary>Looks up a localized string similar to "Maximize".</summary>
    public static string Main_MaximizeTip => Get("Main.MaximizeTip");

    /// <summary>Looks up a localized string similar to "Minimize".</summary>
    public static string Main_MinimizeTip => Get("Main.MinimizeTip");

    /// <summary>Looks up a localized string similar to "New task".</summary>
    public static string Main_NewTask => Get("Main.NewTask");

    /// <summary>Looks up a localized string similar to "Run all".</summary>
    public static string Main_RunAll => Get("Main.RunAll");

    /// <summary>Looks up a localized string similar to "Settings".</summary>
    public static string Main_SettingsTip => Get("Main.SettingsTip");

    /// <summary>Looks up a localized string similar to "Show sidebar".</summary>
    public static string Main_ShowSidebarTip => Get("Main.ShowSidebarTip");

    /// <summary>Looks up a localized string similar to "Sync tasks".</summary>
    public static string Main_SyncTasksHeading => Get("Main.SyncTasksHeading");

    /// <summary>Looks up a localized string similar to "Tasks".</summary>
    public static string Main_TasksHeading => Get("Main.TasksHeading");

    /// <summary>Looks up a localized string similar to "Delete {0} file".</summary>
    public static string MirrorDelete_DeleteCount_One => Get("MirrorDelete.DeleteCount.One");

    /// <summary>Looks up a localized string similar to "Delete {0} files".</summary>
    public static string MirrorDelete_DeleteCount_Other => Get("MirrorDelete.DeleteCount.Other");

    /// <summary>Looks up a localized string similar to "Syncing “{0}” will permanently delete {1} files that are no longer in the sou...".</summary>
    public static string MirrorDelete_ExplanationPermanentFormat => Get("MirrorDelete.ExplanationPermanentFormat");

    /// <summary>Looks up a localized string similar to "Syncing “{0}” will move {1} files to the Recycle Bin — they are no longer in ...".</summary>
    public static string MirrorDelete_ExplanationRecycleFormat => Get("MirrorDelete.ExplanationRecycleFormat");

    /// <summary>Looks up a localized string similar to "Keep them".</summary>
    public static string MirrorDelete_KeepThem => Get("MirrorDelete.KeepThem");

    /// <summary>Looks up a localized string similar to "…and {0} more".</summary>
    public static string MirrorDelete_MoreFormat => Get("MirrorDelete.MoreFormat");

    /// <summary>Looks up a localized string similar to "Move to Recycle Bin".</summary>
    public static string MirrorDelete_MoveToRecycleBin => Get("MirrorDelete.MoveToRecycleBin");

    /// <summary>Looks up a localized string similar to "Review deletions".</summary>
    public static string MirrorDelete_ReviewDeletions => Get("MirrorDelete.ReviewDeletions");

    /// <summary>Looks up a localized string similar to "SyncMaid — confirm deletions".</summary>
    public static string MirrorDelete_WindowTitle => Get("MirrorDelete.WindowTitle");

    /// <summary>Looks up a localized string similar to "Copying".</summary>
    public static string Progress_Copying => Get("Progress.Copying");

    /// <summary>Looks up a localized string similar to "Creating".</summary>
    public static string Progress_Creating => Get("Progress.Creating");

    /// <summary>Looks up a localized string similar to "{0} {1} ({2}/{3})".</summary>
    public static string Progress_LineFormat => Get("Progress.LineFormat");

    /// <summary>Looks up a localized string similar to "Moving".</summary>
    public static string Progress_Moving => Get("Progress.Moving");

    /// <summary>Looks up a localized string similar to "Removing".</summary>
    public static string Progress_Removing => Get("Progress.Removing");

    /// <summary>Looks up a localized string similar to "Syncing".</summary>
    public static string Progress_Syncing => Get("Progress.Syncing");

    /// <summary>Looks up a localized string similar to "About".</summary>
    public static string Settings_AboutLabel => Get("Settings.AboutLabel");

    /// <summary>Looks up a localized string similar to "Close to the system tray instead of exiting".</summary>
    public static string Settings_CloseToTray => Get("Settings.CloseToTray");

    /// <summary>Looks up a localized string similar to "Keeps SyncMaid running in the tray when you close the window, so scheduled an...".</summary>
    public static string Settings_CloseToTrayDesc => Get("Settings.CloseToTrayDesc");

    /// <summary>Looks up a localized string similar to "Done".</summary>
    public static string Settings_Done => Get("Settings.Done");

    /// <summary>Looks up a localized string similar to "Language".</summary>
    public static string Settings_LanguageLabel => Get("Settings.LanguageLabel");

    /// <summary>Looks up a localized string similar to "Start minimized to the system tray".</summary>
    public static string Settings_StartMinimized => Get("Settings.StartMinimized");

    /// <summary>Looks up a localized string similar to "SyncMaid launches hidden with only the tray icon; tasks run as usual. Click t...".</summary>
    public static string Settings_StartMinimizedDesc => Get("Settings.StartMinimizedDesc");

    /// <summary>Looks up a localized string similar to "Startup is turned off for SyncMaid in Windows Task Manager (Startup apps). Tu...".</summary>
    public static string Settings_StartupDisabledByWindows => Get("Settings.StartupDisabledByWindows");

    /// <summary>Looks up a localized string similar to "Startup".</summary>
    public static string Settings_StartupLabel => Get("Settings.StartupLabel");

    /// <summary>Looks up a localized string similar to "Start SyncMaid when Windows starts".</summary>
    public static string Settings_StartWithWindows => Get("Settings.StartWithWindows");

    /// <summary>Looks up a localized string similar to "Opens the main window at sign-in.".</summary>
    public static string Settings_StartWithWindowsDesc => Get("Settings.StartWithWindowsDesc");

    /// <summary>Looks up a localized string similar to "App data folder".</summary>
    public static string Settings_StorageAppData => Get("Settings.StorageAppData");

    /// <summary>Looks up a localized string similar to "Storage".</summary>
    public static string Settings_StorageLabel => Get("Settings.StorageLabel");

    /// <summary>Looks up a localized string similar to "Couldn&apos;t move your data — it was left where it is.".</summary>
    public static string Settings_StorageMoveFailed => Get("Settings.StorageMoveFailed");

    /// <summary>Looks up a localized string similar to "Can&apos;t use {0} — the folder is not writable (a portable install under Program ...".</summary>
    public static string Settings_StorageNotWritableFormat => Get("Settings.StorageNotWritableFormat");

    /// <summary>Looks up a localized string similar to "Next to the app (portable)".</summary>
    public static string Settings_StoragePortable => Get("Settings.StoragePortable");

    /// <summary>Looks up a localized string similar to "Moves your tasks and settings to the new location and restarts SyncMaid.".</summary>
    public static string Settings_SwitchStorageDesc => Get("Settings.SwitchStorageDesc");

    /// <summary>Looks up a localized string similar to "Move data to the app data folder".</summary>
    public static string Settings_SwitchToAppData => Get("Settings.SwitchToAppData");

    /// <summary>Looks up a localized string similar to "Move data next to the app (portable)".</summary>
    public static string Settings_SwitchToPortable => Get("Settings.SwitchToPortable");

    /// <summary>Looks up a localized string similar to "System default".</summary>
    public static string Settings_SystemDefault => Get("Settings.SystemDefault");

    /// <summary>Looks up a localized string similar to "Settings".</summary>
    public static string Settings_Title => Get("Settings.Title");

    /// <summary>Looks up a localized string similar to "Version {0}".</summary>
    public static string Settings_VersionFormat => Get("Settings.VersionFormat");

    /// <summary>Looks up a localized string similar to "Window".</summary>
    public static string Settings_WindowLabel => Get("Settings.WindowLabel");

    /// <summary>Looks up a localized string similar to "Failed".</summary>
    public static string Status_Failed => Get("Status.Failed");

    /// <summary>Looks up a localized string similar to "Failed · {0}".</summary>
    public static string Status_FailedFormat => Get("Status.FailedFormat");

    /// <summary>Looks up a localized string similar to "Needs confirmation".</summary>
    public static string Status_NeedsConfirmation => Get("Status.NeedsConfirmation");

    /// <summary>Looks up a localized string similar to "Never run".</summary>
    public static string Status_NeverRun => Get("Status.NeverRun");

    /// <summary>Looks up a localized string similar to "Synced {0} · {1}".</summary>
    public static string Status_SyncedFormat => Get("Status.SyncedFormat");

    /// <summary>Looks up a localized string similar to "Syncing…".</summary>
    public static string Status_Syncing => Get("Status.Syncing");

    /// <summary>Looks up a localized string similar to "Add destination".</summary>
    public static string Task_AddDestinationTip => Get("Task.AddDestinationTip");

    /// <summary>Looks up a localized string similar to "Remove the destination &quot;{0}&quot; from this task? This can&apos;t be undone.".</summary>
    public static string Task_DeleteDestinationMessageFormat => Get("Task.DeleteDestinationMessageFormat");

    /// <summary>Looks up a localized string similar to "Delete destination?".</summary>
    public static string Task_DeleteDestinationTitle => Get("Task.DeleteDestinationTitle");

    /// <summary>Looks up a localized string similar to "Delete task".</summary>
    public static string Task_DeleteTip => Get("Task.DeleteTip");

    /// <summary>Looks up a localized string similar to "Edit task".</summary>
    public static string Task_EditTip => Get("Task.EditTip");

    /// <summary>Looks up a localized string similar to "All synced".</summary>
    public static string Task_HealthAllSynced => Get("Task.HealthAllSynced");

    /// <summary>Looks up a localized string similar to "{0} of {1} failed".</summary>
    public static string Task_HealthFailedFormat => Get("Task.HealthFailedFormat");

    /// <summary>Looks up a localized string similar to "No destinations".</summary>
    public static string Task_HealthNoDestinations => Get("Task.HealthNoDestinations");

    /// <summary>Looks up a localized string similar to "Partly synced".</summary>
    public static string Task_HealthPartlySynced => Get("Task.HealthPartlySynced");

    /// <summary>Looks up a localized string similar to "next run {0}".</summary>
    public static string Task_NextRunFormat => Get("Task.NextRunFormat");

    /// <summary>Looks up a localized string similar to "This task&apos;s paths overlap task &quot;{0}&quot;; fix the overlap and run again — no file...".</summary>
    public static string Task_OverlapRefusedFormat => Get("Task.OverlapRefusedFormat");

    /// <summary>Looks up a localized string similar to "Run now".</summary>
    public static string Task_RunNowTip => Get("Task.RunNowTip");

    /// <summary>Looks up a localized string similar to "Stop".</summary>
    public static string Task_StopTip => Get("Task.StopTip");

    /// <summary>Looks up a localized string similar to "Trigger error".</summary>
    public static string Task_TriggerErrorBadge => Get("Task.TriggerErrorBadge");

    /// <summary>Looks up a localized string similar to "Automatic trigger error; automatic runs may be temporarily unavailable. You c...".</summary>
    public static string Task_TriggerErrorRecoverableFormat => Get("Task.TriggerErrorRecoverableFormat");

    /// <summary>Looks up a localized string similar to "This task&apos;s trigger failed to start, so it only runs when you run it manually...".</summary>
    public static string Task_TriggerErrorStartFormat => Get("Task.TriggerErrorStartFormat");

    /// <summary>Looks up a localized string similar to "Manual".</summary>
    public static string Task_TriggerManual => Get("Task.TriggerManual");

    /// <summary>Looks up a localized string similar to "Scheduled · {0}".</summary>
    public static string Task_TriggerScheduledFormat => Get("Task.TriggerScheduledFormat");

    /// <summary>Looks up a localized string similar to "Watching".</summary>
    public static string Task_TriggerWatching => Get("Task.TriggerWatching");

    /// <summary>Looks up a localized string similar to "Enter a valid cron expression (e.g. */5 * * * *); times use local time".</summary>
    public static string TaskEditor_CronInvalid => Get("TaskEditor.CronInvalid");

    /// <summary>Looks up a localized string similar to "Cron expression".</summary>
    public static string TaskEditor_CronLabel => Get("TaskEditor.CronLabel");

    /// <summary>Looks up a localized string similar to "Next run (local time): {0}".</summary>
    public static string TaskEditor_CronNextRunFormat => Get("TaskEditor.CronNextRunFormat");

    /// <summary>Looks up a localized string similar to "Valid in local time, but has no upcoming runs".</summary>
    public static string TaskEditor_CronNoUpcoming => Get("TaskEditor.CronNoUpcoming");

    /// <summary>Looks up a localized string similar to "This folder doesn&apos;t exist. Check for typos — the task won&apos;t find anything to ...".</summary>
    public static string TaskEditor_MissingFolderHint => Get("TaskEditor.MissingFolderHint");

    /// <summary>Looks up a localized string similar to "Save task".</summary>
    public static string TaskEditor_Save => Get("TaskEditor.Save");

    /// <summary>Looks up a localized string similar to "Every new change restarts the wait, so one burst of writes becomes one sync r...".</summary>
    public static string TaskEditor_SettleHint => Get("TaskEditor.SettleHint");

    /// <summary>Looks up a localized string similar to "Quiet period".</summary>
    public static string TaskEditor_SettleLabel => Get("TaskEditor.SettleLabel");

    /// <summary>Looks up a localized string similar to "Run after".</summary>
    public static string TaskEditor_SettlePrefix => Get("TaskEditor.SettlePrefix");

    /// <summary>Looks up a localized string similar to "seconds without changes".</summary>
    public static string TaskEditor_SettleSuffix => Get("TaskEditor.SettleSuffix");

    /// <summary>Looks up a localized string similar to "Source folder".</summary>
    public static string TaskEditor_SourceFolderLabel => Get("TaskEditor.SourceFolderLabel");

    /// <summary>Looks up a localized string similar to "This folder overlaps the source of task &quot;{0}&quot; — tasks never share sources.".</summary>
    public static string TaskEditor_SourceOverlapHintFormat => Get("TaskEditor.SourceOverlapHintFormat");

    /// <summary>Looks up a localized string similar to "Task".</summary>
    public static string TaskEditor_Title => Get("TaskEditor.Title");

    /// <summary>Looks up a localized string similar to "Trigger".</summary>
    public static string TaskEditor_TriggerLabel => Get("TaskEditor.TriggerLabel");

    /// <summary>Looks up a localized string similar to "Scheduled".</summary>
    public static string TaskEditor_TriggerScheduled => Get("TaskEditor.TriggerScheduled");

    /// <summary>Looks up a localized string similar to "Watch".</summary>
    public static string TaskEditor_TriggerWatch => Get("TaskEditor.TriggerWatch");

    /// <summary>Looks up a localized string similar to "{0} d ago".</summary>
    public static string Time_DaysAgoFormat => Get("Time.DaysAgoFormat");

    /// <summary>Looks up a localized string similar to "due now".</summary>
    public static string Time_DueNow => Get("Time.DueNow");

    /// <summary>Looks up a localized string similar to "{0} h ago".</summary>
    public static string Time_HoursAgoFormat => Get("Time.HoursAgoFormat");

    /// <summary>Looks up a localized string similar to "in {0} d".</summary>
    public static string Time_InDaysFormat => Get("Time.InDaysFormat");

    /// <summary>Looks up a localized string similar to "in {0} h".</summary>
    public static string Time_InHoursFormat => Get("Time.InHoursFormat");

    /// <summary>Looks up a localized string similar to "in {0} min".</summary>
    public static string Time_InMinutesFormat => Get("Time.InMinutesFormat");

    /// <summary>Looks up a localized string similar to "in under a minute".</summary>
    public static string Time_InUnderAMinute => Get("Time.InUnderAMinute");

    /// <summary>Looks up a localized string similar to "just now".</summary>
    public static string Time_JustNow => Get("Time.JustNow");

    /// <summary>Looks up a localized string similar to "{0} min ago".</summary>
    public static string Time_MinutesAgoFormat => Get("Time.MinutesAgoFormat");

    /// <summary>Looks up a localized string similar to "Exit".</summary>
    public static string Tray_Exit => Get("Tray.Exit");

    /// <summary>Looks up a localized string similar to "Show main window".</summary>
    public static string Tray_ShowMainWindow => Get("Tray.ShowMainWindow");
}
