# Regenerates SyncMaid\Lang\Strings.Designer.cs from SyncMaid\Lang\Strings.resx.
# Run after adding, renaming, or removing keys in the neutral resx:
#   pwsh tools/generate-strings.ps1   (or powershell -File tools/generate-strings.ps1)
#
# The generated class gives every resource key a strongly-typed accessor so a key
# typo is a compile error, and routes lookups through CurrentUICulture so values
# follow runtime language switches (see Services\Localizer.cs).

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$resxPath = Join-Path $root 'SyncMaid\Lang\Strings.resx'
$outPath = Join-Path $root 'SyncMaid\Lang\Strings.Designer.cs'

[xml]$resx = Get-Content -Raw -Encoding UTF8 $resxPath
$entries = @($resx.root.data | Sort-Object { $_.name })

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine(@'
//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Strings.resx by tools/generate-strings.ps1 — do not edit by
//     hand; rerun the script after changing the resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMaid.Lang;

/// <summary>
/// Strongly-typed accessors for the UI string resources in <c>Lang\Strings.resx</c>
/// (dots in resource keys become underscores). Lookups follow
/// <see cref="System.Globalization.CultureInfo.CurrentUICulture"/>, which
/// <c>Localizer.Apply</c> switches at runtime; a missing key falls back to the key
/// itself so a lookup can never throw or return null.
/// </summary>
public static class Strings
{
    /// <summary>The underlying resource manager (used by <c>Localizer</c> for keyed lookups).</summary>
    public static global::System.Resources.ResourceManager ResourceManager { get; } =
        new("SyncMaid.Lang.Strings", typeof(Strings).Assembly);

    private static string Get(string key) =>
        ResourceManager.GetString(key, global::System.Globalization.CultureInfo.CurrentUICulture) ?? key;
'@)

foreach ($entry in $entries)
{
    $key = $entry.name
    $property = $key -replace '\.', '_'
    $value = ($entry.value -replace '\s+', ' ').Trim()
    if ($value.Length -gt 80) { $value = $value.Substring(0, 77) + '...' }
    $summary = [System.Security.SecurityElement]::Escape($value)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("    /// <summary>Looks up a localized string similar to ""$summary"".</summary>")
    [void]$sb.AppendLine("    public static string $property => Get(""$key"");")
}

[void]$sb.AppendLine('}')

# Write UTF-8 with BOM to match the repo's C# file encoding conventions on Windows.
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))
Write-Host "Generated $outPath ($($entries.Count) keys)."
